/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hospital;
import java.sql.*;
import javax.swing.*;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import java.awt.Image;
import java.awt.Color;
/**
 *
 * @author anand
 */
public class Adddoctor extends javax.swing.JFrame {

    /** Creates new form Adddoctor */
    public Adddoctor() {
        initComponents();
    }
    
     public Adddoctor(String msg,int id) {
        initComponents();
        btnadd.setText(msg);
        txtid.setText(String.valueOf(id));
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","Admin");
            String q="select * from Doctor where id=?";
            PreparedStatement st=con.prepareStatement(q);
            st.setInt(1,id);
            ResultSet rs=st.executeQuery();
           long milliseconds = System.currentTimeMillis();
           Date d= new Date(milliseconds);

            long milliseconds1 = System.currentTimeMillis();
            Date b = new Date(milliseconds1);

            int i;
            String n,m,e,u,p,c,g,s;
            while(rs.next()){
                i=rs.getInt(1);
                n=rs.getString(2);
                d=rs.getDate(3);
                m=rs.getString(4);
                e=rs.getString(5);
                u=rs.getString(6);
                p=rs.getString(7);
                b=rs.getDate(8);
                c=rs.getString(9);
                g=rs.getString(10);
                s=rs.getString(11);
                
                txtname.setText(n);
                dcdoj.setDate(d);
                txtmob.setText(m);
                txtemail.setText(e);
                txtusername.setText(u);
                txtusername.setEditable(false);
                txtpassword.setText(p);
                txtpassword.setEditable(false);
                dcdob.setDate(b);
                if(g.equals("Male")){
                    rbmale.setSelected(true);
                }
                else if(g.equals("Female")){
                    rbfemale.setSelected(true);
                }
                else{
                    rbother.setSelected(true);
                }
                txtcity.setText(c);
                txtspe.setText(s);
                
            }
        }
        catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }
    }
     

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderGroup = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        txtmob = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtemail = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        dcdoj = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtspe = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        rbmale = new javax.swing.JRadioButton();
        rbfemale = new javax.swing.JRadioButton();
        rbother = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        dcdob = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        btnadd = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txtpassword = new javax.swing.JPasswordField();
        txtid = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/doctor (1).jpg"))); // NOI18N

        txtname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtmob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtemail.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setText("Enter Name: ");

        jLabel3.setText("Enter Date of joining: ");

        dcdoj.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dcdoj.setDateFormatString("yyyy-MM-dd");

        jLabel4.setText("Enter Mobile No. :");

        jLabel5.setText("Enter Email: ");

        jLabel6.setText("Enter Username: ");

        jLabel7.setText("Enter Password: ");

        txtspe.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtcity.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel9.setText("Enter City: ");

        jLabel10.setText("Select Gender: ");

        rbmale.setBackground(new java.awt.Color(255, 255, 255));
        GenderGroup.add(rbmale);
        rbmale.setText("Male");

        rbfemale.setBackground(new java.awt.Color(255, 255, 255));
        GenderGroup.add(rbfemale);
        rbfemale.setText("Female");

        rbother.setBackground(new java.awt.Color(255, 255, 255));
        GenderGroup.add(rbother);
        rbother.setText("Other");

        jLabel11.setText("Specilization:");

        dcdob.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        dcdob.setDateFormatString("yyyy-MM-dd");

        jLabel8.setText("Select Date of Birth: ");

        btnadd.setBackground(new java.awt.Color(146, 155, 248));
        btnadd.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnadd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/crearte Account.png"))); // NOI18N
        btnadd.setText("Add");
        btnadd.setBorder(null);
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-close-window-30.png"))); // NOI18N
        btnexit.setFocusable(false);
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(240, 255, 204));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-home-30.png"))); // NOI18N
        btnback.setText("Home");
        btnback.setBorder(null);
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel12.setText("Doctor Details");

        txtpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtid.setBackground(new java.awt.Color(255, 255, 255));
        txtid.setForeground(new java.awt.Color(255, 255, 255));
        txtid.setText("0");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(103, 103, 103)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(txtmob, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(txtname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 219, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, dcdob, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                        .add(org.jdesktop.layout.GroupLayout.LEADING, txtusername))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(rbmale, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(rbfemale, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(btnadd, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(rbother, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)))
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 166, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 127, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 70, Short.MAX_VALUE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                            .add(txtemail)
                            .add(dcdoj, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .add(txtcity)
                            .add(txtspe)
                            .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 134, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 133, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 135, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLabel11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtpassword))
                        .add(174, 174, 174))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(20, 20, 20)
                        .add(btnback, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 98, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .add(jPanel1Layout.createSequentialGroup()
                .add(346, 346, 346)
                .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 88, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, btnexit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(txtid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(84, 84, 84))))
            .add(jPanel1Layout.createSequentialGroup()
                .add(333, 333, 333)
                .add(jLabel12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 129, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(btnexit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(2, 2, 2)
                        .add(txtid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jLabel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 84, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jLabel12)
                .add(28, 28, 28)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel2)
                            .add(jLabel3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtname, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(dcdoj, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(19, 19, 19)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel4)
                            .add(jLabel5))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(txtmob, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtemail, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel6)
                            .add(jLabel7))
                        .add(1, 1, 1)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(txtusername, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(txtpassword, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(18, 18, 18)
                        .add(jLabel9))
                    .add(jLabel8))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(txtcity, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(dcdob, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jLabel10)
                            .add(jLabel11))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(rbmale)
                            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                                .add(rbfemale)
                                .add(rbother)
                                .add(txtspe, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(0, 55, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btnadd)
                            .add(btnback))
                        .addContainerGap())))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"DO YOU WANT TO CLOSE APPLICATION","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        String update=btnadd.getText();
        String name=txtname.getText();
        String gender;
        String phone=txtmob.getText();
        String user=txtusername.getText();
        String pass=txtpassword.getText();
        String email=txtemail.getText();
        String city=txtcity.getText();
        String spe=txtspe.getText();
        int id=Integer.parseInt(txtid.getText());
            
        if(rbmale.isSelected()){
            gender="Male";
        }
        else if(rbfemale.isSelected()){
            gender="Female";
        }
        else if(rbother.isSelected()){
            gender="Other";
        }else{
            JOptionPane.showMessageDialog(this,"Please select Gender");
             return;  
        }
        
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please Enter Name");
            txtname.setBackground(new Color(246, 53, 40));
            return;
        }
        if(phone.matches("^[0-9]*$")==false || phone.length()!=10){
            JOptionPane.showMessageDialog(this,"Please check Phone Number");
            txtmob.setBackground(new Color(246, 53, 40));
            return;
        }
        if(user.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please Enter UserName");
            txtusername.setBackground(new Color(246, 53, 40));
            return;
        }
        
        if(email.matches("[a-zA-Z0-9\\-\\.]+@[a-z]+\\.[a-z]{2,3}")==false){
            JOptionPane.showMessageDialog(this,"Please check email");
            txtemail.setBackground(new Color(246, 53, 40));
            return;
        }
         if(city.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please Enter city");
            txtcity.setBackground(new Color(246, 53, 40));
            return;
        }
          if(spe.isEmpty()){
            JOptionPane.showMessageDialog(this,"Please Enter specialization");
            txtspe.setBackground(new Color(246, 53, 40));
            return;
        }
          if(update=="Update"){
//              txtusername.setEditable(false);
//              txtpassword.setEditable(false);
           try{
               
                Class.forName("com.mysql.cj.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","Admin");
                String query="update doctor Set name=?,doj=?,phone=?,email=?,dob=?,city=?,gender=?,specialization=? Where id=?";
                PreparedStatement ps=con.prepareStatement(query);
                ps.setString(1,txtname.getText());
                    try{
                        java.util.Date utilDate1 = dcdoj.getDate();
                        long milliseconds1 = utilDate1.getTime();
                        java.sql.Date sqlDate1 = new java.sql.Date(milliseconds1);
                        ps.setDate(2,sqlDate1);
                    }
                    catch(Exception ex){
                        JOptionPane.showMessageDialog(this,"Please Enter Date of joining");
                        dcdoj.setBackground(new Color(246, 53, 40));
                        return;
                    }

                    ps.setString(3,txtmob.getText());
                    ps.setString(4,txtemail.getText());
                    try{
                        java.util.Date utilDate = dcdob.getDate();
                        long milliseconds = utilDate.getTime();
                        java.sql.Date sqlDate = new java.sql.Date(milliseconds);
                        ps.setDate(5,sqlDate);
                    }
                    catch(Exception ex){
                        JOptionPane.showMessageDialog(this,"Please Enter Date of Birth");
                        dcdob.setBackground(new Color(246, 53, 40));
                        return;
                    }
                    ps.setString(6,txtcity.getText());
                    ps.setString(7,gender);
                    ps.setString(8,txtspe.getText());
                    ps.setInt(9,id);
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Updated succussfully !!!");
                    new viewdoctor().setVisible(true);
                    dispose();
                    return;
           }
           catch(Exception e){
               System.out.println("Error: "+e.getMessage());
           }
        }
         
        if(pass.length()>12 || pass.isEmpty()){
            JOptionPane.showMessageDialog(this,"Invalid password");
            txtpassword.setBackground(new Color(246, 53, 40));
            return;
        }
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","Admin");
            String q="Select * from doctor where username=?";
            PreparedStatement ps1=con.prepareStatement(q);
            ps1.setString(1,user);
            ResultSet rs=ps1.executeQuery();
            if(rs.next()){
                JOptionPane.showMessageDialog(this,"Username is already taken");
                txtusername.setBackground(new Color(246, 53, 40));
            }
            else{
                 try{
                    
                    
                    String query="insert into doctor(name,doj,phone,email,username,password,dob,city,gender,specialization) values(?,?,?,?,?,md5(?),?,?,?,?)";
                    PreparedStatement ps=con.prepareStatement(query);
                    ps.setString(1,txtname.getText());
                    try{
                        java.util.Date utilDate1 = dcdoj.getDate();
                        long milliseconds1 = utilDate1.getTime();
                        java.sql.Date sqlDate1 = new java.sql.Date(milliseconds1);
                        ps.setDate(2,sqlDate1);
                    }
                    catch(Exception ex){
                        JOptionPane.showMessageDialog(this,"Please Enter Date of joining");
                        dcdoj.setBackground(new Color(246, 53, 40));
                        return;
                    }

                    ps.setString(3,txtmob.getText());
                    ps.setString(4,txtemail.getText());
                    ps.setString(5,txtusername.getText());
                    ps.setString(6,txtpassword.getText());
                    try{
                        java.util.Date utilDate = dcdob.getDate();
                        long milliseconds = utilDate.getTime();
                        java.sql.Date sqlDate = new java.sql.Date(milliseconds);
                        ps.setDate(7,sqlDate);
                    }
                    catch(Exception ex){
                        JOptionPane.showMessageDialog(this,"Please Enter Date of Birth");
                        dcdob.setBackground(new Color(246, 53, 40));
                        return;
                    }
                    ps.setString(8,txtcity.getText());
                    ps.setString(9,gender);
                    ps.setString(10,txtspe.getText());
                    ps.executeUpdate();
                    JOptionPane.showMessageDialog(this,"Inserted succussfully !!!");
                    dispose();
                }
                catch(Exception e){
                    System.out.println("Error: "+e.getMessage());
                }
            }
        }
        catch(Exception e){
            System.out.println("Error "+e.getMessage());
        }
                
    }//GEN-LAST:event_btnaddActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Adddoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Adddoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Adddoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Adddoctor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Adddoctor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GenderGroup;
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btnexit;
    private com.toedter.calendar.JDateChooser dcdob;
    private com.toedter.calendar.JDateChooser dcdoj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbfemale;
    private javax.swing.JRadioButton rbmale;
    private javax.swing.JRadioButton rbother;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtemail;
    private javax.swing.JLabel txtid;
    private javax.swing.JTextField txtmob;
    private javax.swing.JTextField txtname;
    private javax.swing.JPasswordField txtpassword;
    private javax.swing.JTextField txtspe;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables

}
