/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hospital;
import javax.swing.*;
/**
 *
 * @author anand
 */
public class admin extends javax.swing.JFrame {

    /** Creates new form admin */
    public admin() {
        initComponents();
    }

     public admin(String user) {
        initComponents();
        lblusername.setText(user);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        Menubar = new javax.swing.JMenuBar();
        Doctor = new javax.swing.JMenu();
        AddDoctor = new javax.swing.JMenuItem();
        ViewDoctor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        addres = new javax.swing.JMenuItem();
        viewrec = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        addpatient = new javax.swing.JMenuItem();
        viewpatient = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        checkdoctor = new javax.swing.JMenuItem();
        book = new javax.swing.JMenuItem();
        viewapp = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        profile = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        logout = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Hello ");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 110, 70, -1));

        lblusername.setBackground(new java.awt.Color(255, 255, 255));
        lblusername.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lblusername.setForeground(new java.awt.Color(0, 204, 204));
        lblusername.setText("Username");
        getContentPane().add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 110, 150, -1));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 255));
        jLabel1.setText("ADMIN DESKTOP");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 30, 400, 40));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 78, 310, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.jpg"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 1360, -1));

        Menubar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        Doctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-doctor-48.png"))); // NOI18N
        Doctor.setText("Doctor");
        Doctor.setFocusable(false);

        AddDoctor.setText("Add Doctor");
        AddDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDoctorActionPerformed(evt);
            }
        });
        Doctor.add(AddDoctor);

        ViewDoctor.setText("View Doctor");
        ViewDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewDoctorActionPerformed(evt);
            }
        });
        Doctor.add(ViewDoctor);

        Menubar.add(Doctor);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/rsz_hospital_information.png"))); // NOI18N
        jMenu2.setText("Receptionist");

        addres.setText("Add Receptionist");
        addres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresActionPerformed(evt);
            }
        });
        jMenu2.add(addres);

        viewrec.setText("View Receptionist");
        viewrec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewrecActionPerformed(evt);
            }
        });
        jMenu2.add(viewrec);

        Menubar.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add new patient.png"))); // NOI18N
        jMenu3.setText("Patient");

        addpatient.setText("Add Patient");
        addpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addpatientActionPerformed(evt);
            }
        });
        jMenu3.add(addpatient);

        viewpatient.setText("View Patient");
        viewpatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpatientActionPerformed(evt);
            }
        });
        jMenu3.add(viewpatient);

        Menubar.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list of members.png"))); // NOI18N
        jMenu4.setText("Appointment");

        checkdoctor.setText("Check Avalaibility");
        checkdoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkdoctorActionPerformed(evt);
            }
        });
        jMenu4.add(checkdoctor);

        book.setText("Book Appointment");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        jMenu4.add(book);

        viewapp.setText("View Appointments");
        viewapp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewappActionPerformed(evt);
            }
        });
        jMenu4.add(viewapp);

        Menubar.add(jMenu4);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-administrator-male-48.png"))); // NOI18N
        jMenu5.setText("Profile");

        profile.setText("View Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        jMenu5.add(profile);

        jMenuItem10.setText("Change password");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem10);

        Menubar.add(jMenu5);

        jMenu6.setForeground(new java.awt.Color(255, 51, 51));
        jMenu6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        jMenu6.setText("Exit");

        logout.setText("Logout");
        logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutActionPerformed(evt);
            }
        });
        jMenu6.add(logout);

        jMenuItem1.setText("Close Application");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem1);

        Menubar.add(jMenu6);

        setJMenuBar(Menubar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void viewpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpatientActionPerformed
        new viewpatient().setVisible(true);
    }//GEN-LAST:event_viewpatientActionPerformed

    private void logoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutActionPerformed
        new Login().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_logoutActionPerformed

    private void AddDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDoctorActionPerformed
        new Adddoctor().setVisible(true);
       
    }//GEN-LAST:event_AddDoctorActionPerformed

    private void ViewDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewDoctorActionPerformed
       new viewdoctor().setVisible(true);
    }//GEN-LAST:event_ViewDoctorActionPerformed

    private void addresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresActionPerformed
        new addrec().setVisible(true);
    }//GEN-LAST:event_addresActionPerformed

    private void viewrecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewrecActionPerformed
        new viewrec().setVisible(true);
    }//GEN-LAST:event_viewrecActionPerformed

    private void addpatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addpatientActionPerformed
        new Addpatient().setVisible(true);
    }//GEN-LAST:event_addpatientActionPerformed

    private void checkdoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkdoctorActionPerformed
        new checkdoctor().setVisible(true);
    }//GEN-LAST:event_checkdoctorActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        new book().setVisible(true);
    }//GEN-LAST:event_bookActionPerformed

    private void viewappActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewappActionPerformed
        new viewappointement().setVisible(true);
    }//GEN-LAST:event_viewappActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        String name="Admin";
        String user=lblusername.getText();
        new adminprofile(name,user).setVisible(true);
    }//GEN-LAST:event_profileActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        String user=lblusername.getText();
        new changepassword(user).setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"DO YOU WANT TO CLOSE APPLICATION","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem AddDoctor;
    private javax.swing.JMenu Doctor;
    private javax.swing.JMenuBar Menubar;
    private javax.swing.JMenuItem ViewDoctor;
    private javax.swing.JMenuItem addpatient;
    private javax.swing.JMenuItem addres;
    private javax.swing.JMenuItem book;
    private javax.swing.JMenuItem checkdoctor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblusername;
    private javax.swing.JMenuItem logout;
    private javax.swing.JMenuItem profile;
    private javax.swing.JMenuItem viewapp;
    private javax.swing.JMenuItem viewpatient;
    private javax.swing.JMenuItem viewrec;
    // End of variables declaration//GEN-END:variables

}
