/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hospital;
import javax.swing.*;


/**
 *
 * @author anand
 */
public class Receptionist extends javax.swing.JFrame {

    /** Creates new form Receptionist */
    public Receptionist() {
        initComponents();
    }

    public Receptionist(String user,int id) {
        initComponents();     
        lblid.setText(String.valueOf(id));
        lblusername.setText(user);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblid = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        viewdoctor = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        add = new javax.swing.JMenuItem();
        view = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        check = new javax.swing.JMenuItem();
        book = new javax.swing.JMenuItem();
        viewappointement = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        profile = new javax.swing.JMenuItem();
        change = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        exit = new javax.swing.JMenuItem();
        close = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblid.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        lblid.setForeground(new java.awt.Color(102, 255, 255));
        lblid.setText("Id");
        getContentPane().add(lblid, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 100, 34, 30));

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 0));
        jLabel2.setText("Hello");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(586, 140, 80, -1));

        lblusername.setFont(new java.awt.Font("Agency FB", 1, 36)); // NOI18N
        lblusername.setForeground(new java.awt.Color(255, 255, 255));
        lblusername.setText("username");
        getContentPane().add(lblusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 140, 140, -1));

        jLabel1.setFont(new java.awt.Font("Algerian", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 0, 255));
        jLabel1.setText("Receptionist Desktop");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, 580, 79));
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 72, 500, 10));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/home.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-doctor-48.png"))); // NOI18N
        jMenu1.setText("Doctor");

        viewdoctor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Details.png"))); // NOI18N
        viewdoctor.setText("View Doctors");
        viewdoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewdoctorActionPerformed(evt);
            }
        });
        jMenu1.add(viewdoctor);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/add new patient.png"))); // NOI18N
        jMenu2.setText("Patient");

        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add new.png"))); // NOI18N
        add.setText("Add patient");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });
        jMenu2.add(add);

        view.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search1.png"))); // NOI18N
        view.setText("View Patient");
        view.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewActionPerformed(evt);
            }
        });
        jMenu2.add(view);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/list of members.png"))); // NOI18N
        jMenu3.setText("Appointment");

        check.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search1.png"))); // NOI18N
        check.setText("Check Availability");
        check.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkActionPerformed(evt);
            }
        });
        jMenu3.add(check);

        book.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add new.png"))); // NOI18N
        book.setText("Book Appointment");
        book.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookActionPerformed(evt);
            }
        });
        jMenu3.add(book);

        viewappointement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Details.png"))); // NOI18N
        viewappointement.setText("View Appointments");
        viewappointement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewappointementActionPerformed(evt);
            }
        });
        jMenu3.add(viewappointement);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-administrator-male-48.png"))); // NOI18N
        jMenu4.setText("Profile");

        profile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/search1.png"))); // NOI18N
        profile.setText("View Profile");
        profile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileActionPerformed(evt);
            }
        });
        jMenu4.add(profile);

        change.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Update details.png"))); // NOI18N
        change.setText("Change Password");
        change.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changeActionPerformed(evt);
            }
        });
        jMenu4.add(change);

        jMenuBar1.add(jMenu4);

        jMenu5.setForeground(new java.awt.Color(255, 51, 51));
        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        jMenu5.setText("Exit");

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Logout.png"))); // NOI18N
        exit.setText("Log Out");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jMenu5.add(exit);

        close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit application.png"))); // NOI18N
        close.setText("Close Application");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jMenu5.add(close);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_exitActionPerformed

    private void viewdoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewdoctorActionPerformed
        String user=lblusername.getText();
        new viewdoctor(user).setVisible(true);
    }//GEN-LAST:event_viewdoctorActionPerformed

    private void viewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewActionPerformed
        new viewpatient().setVisible(true);
    }//GEN-LAST:event_viewActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        new Addpatient().setVisible(true);
    }//GEN-LAST:event_addActionPerformed

    private void checkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkActionPerformed
        new checkdoctor().setVisible(true);
    }//GEN-LAST:event_checkActionPerformed

    private void bookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookActionPerformed
        new book().setVisible(true);
    }//GEN-LAST:event_bookActionPerformed

    private void profileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileActionPerformed
        String name="Receptionist";
        String user=lblusername.getText();
        new adminprofile(name,user).setVisible(true);
    }//GEN-LAST:event_profileActionPerformed

    private void changeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changeActionPerformed
        String user=lblusername.getText();
        new changepassword(user).setVisible(true);
    }//GEN-LAST:event_changeActionPerformed

    private void viewappointementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewappointementActionPerformed
        String name="Receptionist";
        new viewappointement(name).setVisible(true);
    }//GEN-LAST:event_viewappointementActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        int a=JOptionPane.showConfirmDialog(null,"DO YOU WANT TO CLOSE APPLICATION","Select",JOptionPane.YES_NO_OPTION);
        if(a==0){
            System.exit(0);
        }
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Receptionist.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Receptionist().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem add;
    private javax.swing.JMenuItem book;
    private javax.swing.JMenuItem change;
    private javax.swing.JMenuItem check;
    private javax.swing.JMenuItem close;
    private javax.swing.JMenuItem exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblid;
    private javax.swing.JLabel lblusername;
    private javax.swing.JMenuItem profile;
    private javax.swing.JMenuItem view;
    private javax.swing.JMenuItem viewappointement;
    private javax.swing.JMenuItem viewdoctor;
    // End of variables declaration//GEN-END:variables

}
