/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package hospital;
import java.sql.*;
import javax.swing.table.*;
import javax.swing.*;
import java.time.LocalDate;

/**
 *
 * @author anand
 */
public class viewappointement extends javax.swing.JFrame {

    /** Creates new form viewappointement */

    public viewappointement() {
        initComponents();
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","Admin");
            DefaultTableModel model=new DefaultTableModel(new String[]{"Appointment No.","Patient Id","Doctor Id","Problem","Appointment Date","Status"},0);
            Table.setModel(model);
            String sql="select * from appointements";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            String d,s,a;
            int i,pi,di;
            while(rs.next()){
                i=rs.getInt(1);
                pi=rs.getInt(2);
                di=rs.getInt(3);
                a=rs.getString(4);
                d=rs.getString(5);
                s=rs.getString(6);
                
                model.addRow(new Object[]{i,pi,di,d,a,s});
            }
        }
        catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }
    }

    public viewappointement(String name) {
        initComponents();
        getContentPane().add(lblid);
        getContentPane().add(txtid);
        getContentPane().add(btncancel);
        getContentPane().add(btncomplete);
        getContentPane().remove(lblid);
        getContentPane().remove(txtid);
        getContentPane().remove(btncancel);
        getContentPane().remove(btncomplete);
        getContentPane().revalidate();
        getContentPane().repaint();
        
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","Admin");
            DefaultTableModel model=new DefaultTableModel(new String[]{"Appointment No.","Patient Id","Doctor Id","Problem","Appointment Date","Status","Timing"},0);
            Table.setModel(model);
            String sql="select * from appointements";
            Statement st=con.createStatement();
            ResultSet rs=st.executeQuery(sql);
            String d,s,a,t;
            int i,pi,di;
            while(rs.next()){
                i=rs.getInt(1);
                pi=rs.getInt(2);
                di=rs.getInt(3);
                a=rs.getString(4);
                d=rs.getString(5);
                s=rs.getString(6);
                t=rs.getString(7);
                model.addRow(new Object[]{i,pi,di,d,a,s,t});
            }
        }
        catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }
    }
    
    public viewappointement(int id) {
        initComponents();
        java.sql.Date currentDate = Date.valueOf(LocalDate.now());
         try{
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","Admin");
            DefaultTableModel model=new DefaultTableModel(new String[]{"Appointment no.","Patient Id","Doctor Id","Problem","Appointment Date","Status"},0);
            Table.setModel(model);
            String sql="select * from appointements where doctorid=? and appointment_Date=?";
            PreparedStatement st=con.prepareStatement(sql);
            st.setInt(1,id);
            st.setDate(2,currentDate);
            ResultSet rs=st.executeQuery();
            String d,s,a;
            int i,pi,di;
            while(rs.next()){
                i=rs.getInt(1);
                pi=rs.getInt(2);
                di=rs.getInt(3);
                a=rs.getString(4);
                d=rs.getString(5);
                s=rs.getString(6);
                
                model.addRow(new Object[]{i,pi,di,d,a,s});
            }
        }
        catch(Exception e){
            System.out.println("Error: "+e.getMessage());
        }
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnexit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new javax.swing.JTable();
        lblid = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        btncancel = new javax.swing.JButton();
        btncomplete = new javax.swing.JButton();
        btnback = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 199, 137));

        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-close-window-30.png"))); // NOI18N
        btnexit.setFocusable(false);
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Appointment No.", "Patient Id", "Doctor Id", "Problem", "Appointement Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        lblid.setBackground(new java.awt.Color(0, 153, 255));
        lblid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblid.setForeground(new java.awt.Color(102, 102, 255));
        lblid.setText("Enter Appointment Id: ");

        btncancel.setBackground(new java.awt.Color(255, 51, 102));
        btncancel.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Exit application.png"))); // NOI18N
        btncancel.setText("Appointment canceled");
        btncancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelActionPerformed(evt);
            }
        });

        btncomplete.setBackground(new java.awt.Color(204, 153, 0));
        btncomplete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btncomplete.setForeground(new java.awt.Color(255, 255, 255));
        btncomplete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-checkmark-30.png"))); // NOI18N
        btncomplete.setText("Appointment completed");
        btncomplete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncompleteActionPerformed(evt);
            }
        });

        btnback.setBackground(new java.awt.Color(51, 0, 51));
        btnback.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnback.setForeground(new java.awt.Color(255, 255, 255));
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/icons8-home-30.png"))); // NOI18N
        btnback.setText("Home");
        btnback.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Agency FB", 1, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 0, 255));
        jLabel2.setText("Appointment Details");

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane1)
            .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 366, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(233, 233, 233)
                    .add(btnexit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 23, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .add(lblid)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                    .add(txtid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(18, 18, 18)
                    .add(btncancel)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(btncomplete)
                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                    .add(btnback, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 90, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(btnexit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(52, 52, 52))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jLabel2)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)))
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 203, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(lblid, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
                    .add(txtid, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btncancel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btncomplete, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(btnback, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        dispose();
    }//GEN-LAST:event_btnbackActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnexitActionPerformed

    private void btncancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelActionPerformed
        String i=txtid.getText();
        if(i.isEmpty()||i.matches("[a-zA-z]")){
            JOptionPane.showMessageDialog(this,"Please Enter Valid id");
            return;
        }
        int id=Integer.parseInt(i);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","Admin");
            String q="update appointements set status=? where id=?";
            PreparedStatement ps=con.prepareStatement(q);
            ps.setString(1,"Canceled");
            ps.setInt(2,id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Appointment Canceled of Appointment Number "+id);
            new viewappointement().setVisible(true);
            dispose();
        }
        catch(Exception e){
            System.out.println("Error "+e.getMessage());
             JOptionPane.showMessageDialog(this,"Error");
        }
    }//GEN-LAST:event_btncancelActionPerformed

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        int i=Table.getSelectedRow();
        TableModel model=Table.getModel();
        txtid.setText(model.getValueAt(i,0).toString());
    }//GEN-LAST:event_TableMouseClicked

    private void btncompleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncompleteActionPerformed
       String i=txtid.getText();
        if(i.isEmpty()||i.matches("[a-zA-z]")){
            JOptionPane.showMessageDialog(this,"Please Enter Valid id");
            return;
        }
        int id=Integer.parseInt(i);
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","Admin");
            String q="update appointements set status=? where id=?";
            PreparedStatement ps=con.prepareStatement(q);
            ps.setString(1,"Completed");
            ps.setInt(2,id);
            ps.executeUpdate();
            JOptionPane.showMessageDialog(this,"Appointment Completed of Appointment Number "+id);
            new viewappointement().setVisible(true);
            dispose();
        }
        catch(Exception e){
            System.out.println("Error "+e.getMessage());
             JOptionPane.showMessageDialog(this,"Error");
        }
    }//GEN-LAST:event_btncompleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewappointement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewappointement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewappointement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewappointement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewappointement().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Table;
    private javax.swing.JButton btnback;
    private javax.swing.JButton btncancel;
    private javax.swing.JButton btncomplete;
    private javax.swing.JButton btnexit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblid;
    private javax.swing.JTextField txtid;
    // End of variables declaration//GEN-END:variables

}
